### ISSUE TITLE
"Defenition" spelled incorrectly

### ISSUE THREAD

**Issue by XMB5** [payamnj/owlbot#1]
`[
    {
        "type": "noun",
        "defenition": "a nocturnal bird of prey with large eyes, a facial disc, a hooked beak, and typically a loud hooting call.",
        "example": "I love reaching out into that absolute silence, when you can hear the owl or the wind."
    }
]`

defenition should be definition

**Comment by payamnj** [comment]
Thanks @XMB5.  it should be fine now if you access the API from `/api/v2/dictionary/`
