### ISSUE TITLE
Can't access the repository on bitbucket

### ISSUE THREAD

**Issue by zambrey** [payamnj/owlbot#5]
![image](https://user-images.githubusercontent.com/2551964/87560520-64eb4b00-c670-11ea-90b1-02e5aa510106.png)

Is this intended?

**Comment by payamnj** [comment]
Hi Ameya,

Yes, the repository was public first but for security reasons I’ve decided
to make it private.

Kind Regards,
Payam

**Comment by zambrey** [comment]
Oh that's too bad. Would have been interesting to see the implementation.
